blank_issues_enabled: true
contact_links:
  - name: Twitter Support
    url: https://twitter.com/alchemistake
    about: Quick questions or feedback via Twitter
  - name: Discussions
    url: https://github.com/alchemistake/pokeproxy/discussions
    about: General discussions, questions, and community interaction
